services:
    updatecerts:
        image: vjedev/certupdater:latest
        volumes:
            - certs:/certs
            - mysqlconf:/mysqlconf
    landingpage:
        image: vjedev/landingpage:latest
        volumes:
            - ./websites:/websites
    databaseimportexport:
        image: vjedev/database-import-export:latest
        volumes:
            - ./websites:/websites
        depends_on:
            - mysql
    web:
        image: nginx:1.27.5-alpine3.21
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/nginx.conf
            - certs:/certs
            - ./websites:/websites
        depends_on:
            - updatecerts
    php:
        build:
            context: .
            dockerfile: PHP.Dockerfile
        volumes:
            - ./websites:/websites
    mysql:
        image: mariadb:11.7.2-noble 
        environment:
            MYSQL_ROOT_PASSWORD: 'v.je'
            MYSQL_USER: 'v.je'
            MYSQL_PASSWORD: 'v.je'
        volumes:
            - mysqldata:/var/lib/mysql
            - certs:/ssl
            - mysqlconf:/etc/mysql/conf.d/
        ports:
            - 3306:3306
    phpunit:
        build:
            context: .
            dockerfile: PHP.Dockerfile
        working_dir: /websites/default
        entrypoint: 'vendor/bin/phpunit'
        volumes:
            - ./websites:/websites
        profiles:
            - phpunit
    composer:
        build:
            context: .
            dockerfile: PHP.Dockerfile
        working_dir: /websites/default
        entrypoint: /usr/bin/composer
        volumes:
            - ./websites:/websites
        profiles:
            - composer
    maildev:
        image: maildev/maildev:latest
    
    phpmyadmin:
        image: phpmyadmin:5.2.2-apache
        environment:
            PMA_HOST: mysql
            PMA_USER: v.je
            PMA_PASSWORD: v.je
        ports:
            - 8080:80
        depends_on:
            - mysql

volumes:
    mysqldata: {}
    certs: {}
    mysqlconf: {}
